newfigc3s3.1 <-
function() {
   postscript("nfigc3s3.1.ps",pointsize=14)
   dumx<-runif(100,0,15)
   dumy<-runif(100,0,.30)
   par(mfrow=c(2,1))
   plot(dumx,dumy,axes=T,xlim=c(0,15),ylim=c(0,.30),pch=" ",xlab=expression(x),ylab=expression(f(x)))
#  text(-.1,.13,"f(x)")
#  text(35,-.1,"x")
   x<-seq(0,34,.1)
#  y<-dgamma(x,shape=2,scale=4)
   y<-dgamma(x,shape=.25,scale=4)
   lines(x,y)
   text(2.3,.250,expression(paste(alpha," = .25")),cex=2)
#   y<-dgamma(x,shape=3,scale=4)
    y<-dgamma(x,shape=.5,scale=4)
   lines(x,y)
   text(1,.040,expression(paste(alpha," = .5")),cex=2)
#  y<-dgamma(x,shape=4,scale=4)
   y<-dgamma(x,shape=1,scale=4)
   lines(x,y)
   text(6,.100,expression(paste(alpha," = 1")),cex=2)
   title(main=expression(paste(beta," = 4")),cex=2)

   dumx<-runif(100,0,34)
   dumy<-runif(100,0,.13)
   plot(dumx,dumy,axes=T,xlim=c(0,34),ylim=c(0,.12),pch=" ",xlab="x",ylab="f(x)")
   title(main=expression(paste(alpha," = 4")),cex=2)
   y<-dgamma(x,shape=4,scale=2)
   lines(x,y)
   text(10.0,.100,expression(paste(beta," = 2")),cex=2)
   y<-dgamma(x,shape=4,scale=3)
   lines(x,y)
   text(14.0,.070,expression(paste(beta," = 3")),cex=2)
   y<-dgamma(x,shape=4,scale=4)
   lines(x,y)
   text(22.0,.040,expression(paste(beta," = 4")),cex=2)

 dev.off()
}
